---
- name: Block IP using iptables
  hosts: all
  become: yes
  tasks:
    - name: Add iptables rule to block IP
      ansible.builtin.iptables:
        chain: INPUT
        source: "{{ ip_to_block }}"
        jump: DROP
      register: iptables_result
    - name: Save iptables rules
      ansible.builtin.command: iptables-save > /etc/iptables/rules.v4
      when: iptables_result.changed
