---
- name: Block malicious IP using iptables
  hosts: all
  become: yes
  vars:
    malicious_ip: "{{ hostvars[inventory_hostname].malicious_ip }}"
    
  tasks:
    - name: Block IP with iptables
      iptables:
        chain: INPUT
        source: "{{ malicious_ip }}"
        jump: DROP
        comment: "Blocked by AWX at {{ ansible_date_time.iso8601 }}"
        action: insert
      notify: save iptables
    
    - name: Also block in DOCKER-USER chain (for containers)
      iptables:
        chain: DOCKER-USER
        source: "{{ malicious_ip }}"
        jump: DROP
        comment: "Blocked by AWX at {{ ansible_date_time.iso8601 }}"
        action: insert
      notify: save iptables
    
    handlers:
    - name: save iptables
      command: /sbin/iptables-save > /etc/iptables/rules.v4
      listen: "save iptables"
