---
- name: Block malicious IP using iptables (Host Version)
  hosts: all
  become: yes
  vars:
    malicious_ip: "{{ malicious_ip }}"
    
  tasks:
    - name: Block IP in INPUT chain
      ansible.builtin.command: |
        /sbin/iptables -I INPUT -s {{ malicious_ip }} -j DROP &&
        /sbin/iptables -I DOCKER-USER -s {{ malicious_ip }} -j DROP
      args:
        executable: /bin/bash
      changed_when: true
      notify: save iptables

    - name: Ensure persistent rules
      ansible.builtin.copy:
        dest: /etc/iptables/rules.v4
        content: "{{ lookup('ansible.builtin.file', '/etc/iptables/rules.v4') }}"
      when: ansible_facts.os_family == 'Debian'
      notify: reload iptables

  handlers:
    - name: save iptables
      ansible.builtin.command: /sbin/iptables-save > /etc/iptables/rules.v4
      changed_when: true

    - name: reload iptables
      ansible.builtin.service:
        name: netfilter-persistent
        state: reloaded
      when: ansible_facts.os_family == 'Debian'
