- name: Manage UFW rules
  hosts: 192.168.3.160
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Block IP using UFW
      ufw:
        rule: deny
        from_ip: "{{ ip_address }}"
      delegate_to: 192.168.3.160
