- name: Manage UFW rules
  hosts: 192.168.3.160
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Debug all variables
      debug:
        msg: "All variables: {{ vars | to_json }}"
      delegate_to: 192.168.3.160

    - name: Debug job extra vars
      debug:
        msg: "Job extra vars: {{ job_extra_vars | default('not defined') | to_json }}"
      delegate_to: 192.168.3.160

    - name: Debug ansible extra vars
      debug:
        msg: "Ansible extra vars: {{ ansible_extra_vars | default('not defined') | to_json }}"
      delegate_to: 192.168.3.160

    - name: Debug all job inputs
      debug:
        msg: "All job inputs: {{ lookup('vars', 'ansible_playbook_python') | default({}) | combine(vars) | to_json }}"
      delegate_to: 192.168.3.160

    - name: Extract IP from observable
      set_fact:
        ip_address: "{{ data | default(job_extra_vars.data | default(ansible_extra_vars.data | default(vars.data | default('')))) }}"
      delegate_to: 192.168.3.160

    - name: Debug extracted IP
      debug:
        msg: "IP address to block: {{ ip_address }}"
      when: ip_address | length > 0
      delegate_to: 192.168.3.160

    - name: Block IP using UFW
      ufw:
        rule: deny
        from_ip: "{{ ip_address }}"
      when: ip_address | length > 0 and ip_address is regex('^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$')
      delegate_to: 192.168.3.160
