---
- name: Block IP with iptables (Confirmed Working Version)
  hosts: all
  become: yes
  vars:
    malicious_ip: "{{ malicious_ip }}"
    iptables_path: "/usr/sbin/iptables"  # Sử dụng đường dẫn đã xác nhận
    
  tasks:
    - name: Block IP in INPUT and DOCKER-USER chains
      ansible.builtin.shell: |
        {{ iptables_path }} -I INPUT -s {{ malicious_ip }} -j DROP && 
        {{ iptables_path }} -I DOCKER-USER -s {{ malicious_ip }} -j DROP
      args:
        executable: /bin/bash
      notify: save iptables

    - name: Ensure rules persistence
      block:
        - name: Install iptables-persistent (Debian/Ubuntu)
          ansible.builtin.apt:
            name: iptables-persistent
            state: present
          when: ansible_facts.os_family == 'Debian'

        - name: Install iptables-services (RHEL/CentOS)
          ansible.builtin.yum:
            name: iptables-services
            state: present
          when: ansible_facts.os_family == 'RedHat'
      when: ansible_facts.os_family in ['Debian', 'RedHat']

  handlers:
    - name: save iptables
      ansible.builtin.shell: "{{ iptables_path }}-save > /etc/iptables/rules.v4"
      args:
        executable: /bin/bash
